/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

//-------------------------------------------------------------------------
// Function declarations

void (*init_proc())(void);
void sub_710();
// char *strncpy(char *dest, const char *src, size_t n);
// int puts(const char *s);
// int system(const char *command);
// int printf(const char *format, ...);
// int __fastcall __libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// char *fgets(char *s, int n, FILE *stream);
// int __fastcall __cxa_finalize(void *);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
__int64 (**call_gmon_start())(void);
void _do_global_dtors_aux();
__int64(__fastcall** frame_dummy())(_QWORD);
int secret_backdoor();
int handle_msg();
char* __fastcall set_msg(__int64 a1);
int __fastcall set_username(__int64 a1);
int __fastcall main(int argc, const char** argv, const char** envp);
void (*_libc_csu_init())(void);
__int64 __fastcall _libc_csu_fini(); // weak
void (*_do_global_ctors_aux())(void);
void term_proc();
// int __fastcall _cxa_finalize(void *);
// __int64 _gmon_start__(void); weak
// __int64 __fastcall Jv_RegisterClasses(_QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

__int64 _CTOR_LIST__ = -1LL; // weak
__int64 _DTOR_LIST__[] = { -1LL }; // weak
__int64 _DTOR_END__ = 0LL; // weak
__int64 _JCR_LIST__ = 0LL; // weak
void* _dso_handle = &_dso_handle; // idb
char completed_6531; // weak
__int64 dtor_idx_6533; // weak
// extern struct _IO_FILE *stdin;

//----- (00000000000006F0) ----------------------------------------------------
void (*init_proc())(void)
{
    call_gmon_start();
    frame_dummy();
    return _do_global_ctors_aux();
}

//----- (0000000000000710) ----------------------------------------------------
void sub_710()
{
    JUMPOUT(0LL);
}
// 716: control flows out of bounds to 0

//----- (0000000000000790) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
    __int64 v3; // rax
    int v4; // esi
    __int64 v5; // [rsp-8h] [rbp-8h] BYREF
    char* retaddr; // [rsp+0h] [rbp+0h] BYREF

    v4 = v5;
    v5 = v3;
    __libc_start_main(
        (int(__fastcall*)(int, char**, char**))main,
        v4,
        &retaddr,
        (void (*)(void))_libc_csu_init,
        (void (*)(void))_libc_csu_fini,
        a3,
        &v5);
    __halt();
}
// 796: positive sp value 8 has been found
// 79D: variable 'v3' is possibly undefined
// B60: using guessed type __int64 __fastcall _libc_csu_fini();

//----- (00000000000007BC) ----------------------------------------------------
__int64 (**call_gmon_start())(void)
{
    __int64 (**result)(void); // rax

    result = &_gmon_start__;
    if (&_gmon_start__)
        return (__int64 (**)(void))_gmon_start__();
    return result;
}
// 2021D8: using guessed type __int64 _gmon_start__(void);

//----- (00000000000007E0) ----------------------------------------------------
void _do_global_dtors_aux()
{
    __int64 v0; // rax
    unsigned __int64 i; // rbx

    if (!completed_6531) {
        if (&_cxa_finalize)
            __cxa_finalize(_dso_handle);
        v0 = dtor_idx_6533;
        for (i = &_DTOR_END__ - _DTOR_LIST__ - 1; dtor_idx_6533 < i; v0 = dtor_idx_6533) {
            dtor_idx_6533 = v0 + 1;
            ((void (*)(void))_DTOR_LIST__[v0 + 1])();
        }
        completed_6531 = 1;
    }
}
// 201E08: using guessed type __int64 _DTOR_LIST__[];
// 201E10: using guessed type __int64 _DTOR_END__;
// 202060: using guessed type char completed_6531;
// 202068: using guessed type __int64 dtor_idx_6533;

//----- (0000000000000860) ----------------------------------------------------
__int64(__fastcall** frame_dummy())(_QWORD)
{
    __int64(__fastcall * *result)(_QWORD); // rax

    if (_JCR_LIST__) {
        result = &Jv_RegisterClasses;
        if (&Jv_RegisterClasses)
            return (__int64(__fastcall**)(_QWORD))Jv_RegisterClasses(&_JCR_LIST__);
    }
    return result;
}
// 201E18: using guessed type __int64 _JCR_LIST__;
// 2021E0: using guessed type __int64 __fastcall Jv_RegisterClasses(_QWORD);

//----- (000000000000088C) ----------------------------------------------------
int secret_backdoor()
{
    char s[128]; // [rsp+0h] [rbp-80h] BYREF

    fgets(s, 128, stdin);
    return system(s);
}

//----- (00000000000008C0) ----------------------------------------------------
int handle_msg()
{
    char v1[140]; // [rsp+0h] [rbp-C0h] BYREF
    __int64 v2; // [rsp+8Ch] [rbp-34h]
    __int64 v3; // [rsp+94h] [rbp-2Ch]
    __int64 v4; // [rsp+9Ch] [rbp-24h]
    __int64 v5; // [rsp+A4h] [rbp-1Ch]
    __int64 v6; // [rsp+ACh] [rbp-14h]
    int v7; // [rsp+B4h] [rbp-Ch]

    v2 = 0LL;
    v3 = 0LL;
    v4 = 0LL;
    v5 = 0LL;
    v6 = 0LL;
    v7 = 140;
    set_username((__int64)v1);
    set_msg((__int64)v1);
    return puts(">: Msg sent!");
}

//----- (0000000000000932) ----------------------------------------------------
char* __fastcall set_msg(__int64 a1)
{
    char s[1024]; // [rsp+10h] [rbp-400h] BYREF

    memset(s, 0, sizeof(s));
    puts(">: Msg @Unix-Dude");
    printf(">>: ");
    fgets(s, 1024, stdin);
    return strncpy((char*)a1, s, *(int*)(a1 + 180));
}

//----- (00000000000009CD) ----------------------------------------------------
int __fastcall set_username(__int64 a1)
{
    char s[140]; // [rsp+10h] [rbp-90h] BYREF
    int i; // [rsp+9Ch] [rbp-4h]

    memset(s, 0, 0x80uLL);
    puts(">: Enter your username");
    printf(">>: ");
    fgets(s, 128, stdin);
    for (i = 0; i <= 40 && s[i]; ++i)
        *(_BYTE*)(a1 + i + 140) = s[i];
    return printf(">: Welcome, %s", (const char*)(a1 + 140));
}
// 9CD: using guessed type char s[140];

//----- (0000000000000AA8) ----------------------------------------------------
int __fastcall main(int argc, const char** argv, const char** envp)
{
    puts(
        "--------------------------------------------\n"
        "|   ~Welcome to l33t-m$n ~    v1337        |\n"
        "--------------------------------------------");
    handle_msg();
    return 0;
}

//----- (0000000000000AD0) ----------------------------------------------------
void (*_libc_csu_init())(void)
{
    return init_proc();
}

//----- (0000000000000B70) ----------------------------------------------------
void (*_do_global_ctors_aux())(void)
{
    void (*result)(void); // rax
    void (**v1)(void); // rbx

    result = (void (*)(void))_CTOR_LIST__;
    if (_CTOR_LIST__ != -1) {
        v1 = (void (**)(void)) & _CTOR_LIST__;
        do {
            --v1;
            result();
            result = *v1;
        } while (*v1 != (void (*)(void)) - 1LL);
    }
    return result;
}
// 201DF8: using guessed type __int64 _CTOR_LIST__;

//----- (0000000000000BA8) ----------------------------------------------------
void term_proc()
{
    _do_global_dtors_aux();
}

// nfuncs=30 queued=14 decompiled=14 lumina nreq=0 worse=0 better=0
// ALL OK, 14 function(s) have been successfully decompiled
