/* This file was generated by the Hex-Rays decompiler version 8.2.0.221215.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

//-------------------------------------------------------------------------
// Function declarations

void (*init_proc())(void);
void sub_4006E0();
// char *strcpy(char *dest, const char *src);
// ssize_t write(int fd, const void *buf, size_t n);
// int fclose(FILE *stream);
// int printf(const char *format, ...);
// int snprintf(char *s, size_t maxlen, const char *format, ...);
// char *strncat(char *dest, const char *src, size_t n);
// int fgetc(FILE *stream);
// int close(int fd);
// size_t strcspn(const char *s, const char *reject);
// int __fastcall __libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int fprintf(FILE *stream, const char *format, ...);
// int open(const char *file, int oflag, ...);
// FILE *fopen(const char *filename, const char *modes);
// void __noreturn exit(int status);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
__int64 (**call_gmon_start())(void);
void _do_global_dtors_aux();
void frame_dummy();
unsigned __int64 __fastcall log_wrapper(FILE* a1, const char* a2, const char* a3);
int __cdecl main(int argc, const char** argv, const char** envp);
void _libc_csu_init(void); // idb
void _libc_csu_fini(void); // idb
void (*_do_global_ctors_aux())(void);
void term_proc();
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

__int64 _CTOR_LIST__ = -1LL; // weak
__int64 _DTOR_LIST__[] = { -1LL }; // weak
__int64 _DTOR_END__ = 0LL; // weak
char completed_6531; // weak
__int64 dtor_idx_6533; // weak

//----- (00000000004006C0) ----------------------------------------------------
void (*init_proc())(void)
{
    call_gmon_start();
    frame_dummy();
    return _do_global_ctors_aux();
}

//----- (00000000004006E0) ----------------------------------------------------
void sub_4006E0()
{
    JUMPOUT(0LL);
}
// 4006E6: control flows out of bounds to 0

//----- (00000000004007E0) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
    __int64 v3; // rax
    int v4; // esi
    __int64 v5; // [rsp-8h] [rbp-8h] BYREF
    char* retaddr; // [rsp+0h] [rbp+0h] BYREF

    v4 = v5;
    v5 = v3;
    __libc_start_main(
        (int(__fastcall*)(int, char**, char**))main,
        v4,
        &retaddr,
        _libc_csu_init,
        _libc_csu_fini,
        a3,
        &v5);
    __halt();
}
// 4007E6: positive sp value 8 has been found
// 4007ED: variable 'v3' is possibly undefined

//----- (000000000040080C) ----------------------------------------------------
__int64 (**call_gmon_start())(void)
{
    __int64 (**result)(void); // rax

    result = &_gmon_start__;
    if (&_gmon_start__)
        return (__int64 (**)(void))_gmon_start__();
    return result;
}
// 6020A0: using guessed type __int64 _gmon_start__(void);

//----- (0000000000400830) ----------------------------------------------------
void _do_global_dtors_aux()
{
    __int64 v0; // rax
    unsigned __int64 i; // rbx

    if (!completed_6531) {
        v0 = dtor_idx_6533;
        for (i = &_DTOR_END__ - _DTOR_LIST__ - 1; dtor_idx_6533 < i; v0 = dtor_idx_6533) {
            dtor_idx_6533 = v0 + 1;
            ((void (*)(void))_DTOR_LIST__[v0 + 1])();
        }
        completed_6531 = 1;
    }
}
// 601DA0: using guessed type __int64 _DTOR_LIST__[];
// 601DA8: using guessed type __int64 _DTOR_END__;
// 602010: using guessed type char completed_6531;
// 602018: using guessed type __int64 dtor_idx_6533;

//----- (00000000004008A0) ----------------------------------------------------
void frame_dummy()
{
    ;
}

//----- (00000000004008C4) ----------------------------------------------------
unsigned __int64 __fastcall log_wrapper(FILE* a1, const char* a2, const char* a3)
{
    char dest[264]; // [rsp+20h] [rbp-110h] BYREF
    unsigned __int64 v6; // [rsp+128h] [rbp-8h]

    v6 = __readfsqword(0x28u);
    strcpy(dest, a2);
    snprintf(&dest[strlen(dest)], 254 - strlen(dest), a3);
    dest[strcspn(dest, "\n")] = 0;
    fprintf(a1, "LOG: %s\n", dest);
    return __readfsqword(0x28u) ^ v6;
}
// 4008C4: using guessed type char dest[264];

//----- (00000000004009F0) ----------------------------------------------------
int __cdecl main(int argc, const char** argv, const char** envp)
{
    FILE* v4; // [rsp+28h] [rbp-88h]
    FILE* stream; // [rsp+30h] [rbp-80h]
    int fd; // [rsp+38h] [rbp-78h]
    char buf; // [rsp+3Fh] [rbp-71h] BYREF
    char dest[104]; // [rsp+40h] [rbp-70h] BYREF
    unsigned __int64 v9; // [rsp+A8h] [rbp-8h]

    v9 = __readfsqword(0x28u);
    buf = -1;
    if (argc != 2)
        printf("Usage: %s filename\n", *argv);
    v4 = fopen("./backups/.log", "w");
    if (!v4) {
        printf("ERROR: Failed to open %s\n", "./backups/.log");
        exit(1);
    }
    log_wrapper(v4, "Starting back up: ", argv[1]);
    stream = fopen(argv[1], "r");
    if (!stream) {
        printf("ERROR: Failed to open %s\n", argv[1]);
        exit(1);
    }
    strcpy(dest, "./backups/");
    strncat(dest, argv[1], 99 - strlen(dest));
    fd = open(dest, 193, 432LL);
    if (fd < 0) {
        printf("ERROR: Failed to open %s%s\n", "./backups/", argv[1]);
        exit(1);
    }
    while (1) {
        buf = fgetc(stream);
        if (buf == -1)
            break;
        write(fd, &buf, 1uLL);
    }
    log_wrapper(v4, "Finished back up ", argv[1]);
    fclose(stream);
    close(fd);
    return 0;
}

//----- (0000000000400C60) ----------------------------------------------------
void _libc_csu_init(void)
{
    init_proc();
}

//----- (0000000000400D00) ----------------------------------------------------
void (*_do_global_ctors_aux())(void)
{
    void (*result)(void); // rax
    void (**v1)(void); // rbx

    result = (void (*)(void))_CTOR_LIST__;
    if (_CTOR_LIST__ != -1) {
        v1 = (void (**)(void)) & _CTOR_LIST__;
        do {
            --v1;
            result();
            result = *v1;
        } while (*v1 != (void (*)(void)) - 1LL);
    }
    return result;
}
// 601D90: using guessed type __int64 _CTOR_LIST__;

//----- (0000000000400D38) ----------------------------------------------------
void term_proc()
{
    _do_global_dtors_aux();
}

// nfuncs=43 queued=11 decompiled=11 lumina nreq=0 worse=0 better=0
// ALL OK, 11 function(s) have been successfully decompiled
