/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

//-------------------------------------------------------------------------
// Function declarations

void (*init_proc())(void);
int sub_8048490();
// int fflush(FILE *stream);
// char *gets(char *s);
// int getchar(void);
// __sighandler_t signal(int sig, __sighandler_t handler);
// unsigned int alarm(unsigned int seconds);
// __pid_t wait(void *stat_loc);
// int puts(const char *s);
// int __gmon_start__(void); weak
// int kill(__pid_t pid, int sig);
// int __cdecl __libc_start_main(int (__cdecl *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int prctl(int option, ...);
// __pid_t fork(void);
// int __cdecl __isoc99_scanf(_DWORD, _DWORD); weak
// int ptrace(enum __ptrace_request request, ...);
// void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>);
void _do_global_dtors_aux();
int frame_dummy();
int clear_stdin();
int get_unum();
void __cdecl __noreturn prog_timeout(int a1);
unsigned int enable_timeout_cons();
int __cdecl main(int argc, const char** argv, const char** envp);
void _libc_csu_init(void); // idb
void _libc_csu_fini(void); // idb
void (*_do_global_ctors_aux())(void);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN unk_8048900; // weak
int (*_init_array_start)() = &enable_timeout_cons; // weak
int _CTOR_LIST__ = -1; // weak
int _DTOR_LIST__[] = { -1 }; // weak
int _DTOR_END__ = 0; // weak
int _JCR_LIST__ = 0; // weak
Elf32_Dyn* GLOBAL_OFFSET_TABLE_ = &DYNAMIC; // weak
int (*dword_8049FFC)(void) = NULL; // weak
FILE* stdout; // idb
char completed_6159; // weak
int dtor_idx_6161; // weak
// extern _UNKNOWN _gmon_start__; weak

//----- (0804845C) --------------------------------------------------------
void (*init_proc())(void)
{
    if (&_gmon_start__)
        __gmon_start__();
    frame_dummy();
    return _do_global_ctors_aux();
}
// 8048510: using guessed type int __gmon_start__(void);

//----- (08048490) --------------------------------------------------------
int sub_8048490()
{
    return dword_8049FFC();
}
// 8049FFC: using guessed type int (*dword_8049FFC)(void);

//----- (08048580) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(int a1 @<eax>, void (*a2)(void) @<edx>)
{
    int v2; // esi
    int v3; // [esp-4h] [ebp-4h] BYREF
    char* retaddr; // [esp+0h] [ebp+0h] BYREF

    v2 = v3;
    v3 = a1;
    __libc_start_main((int(__cdecl*)(int, char**, char**))main, v2, &retaddr, _libc_csu_init, _libc_csu_fini, a2, &v3);
    __halt();
}
// 8048583: positive sp value 4 has been found

//----- (080485B0) --------------------------------------------------------
void _do_global_dtors_aux()
{
    int v0; // eax
    unsigned int i; // ebx

    if (!completed_6159) {
        v0 = dtor_idx_6161;
        for (i = &_DTOR_END__ - _DTOR_LIST__ - 1; dtor_idx_6161 < i; v0 = dtor_idx_6161) {
            dtor_idx_6161 = v0 + 1;
            ((void (*)(void))_DTOR_LIST__[v0 + 1])();
        }
        completed_6159 = 1;
    }
}
// 8049F0C: using guessed type int _DTOR_LIST__[];
// 8049F10: using guessed type int _DTOR_END__;
// 804A044: using guessed type char completed_6159;
// 804A048: using guessed type int dtor_idx_6161;

//----- (08048610) --------------------------------------------------------
int frame_dummy()
{
    int result; // eax

    result = _JCR_LIST__;
    if (_JCR_LIST__)
        return 0;
    return result;
}
// 8049F14: using guessed type int _JCR_LIST__;

//----- (08048634) --------------------------------------------------------
int clear_stdin()
{
    int result; // eax

    do
        result = getchar();
    while ((_BYTE)result != 10 && (_BYTE)result != 0xFF);
    return result;
}

//----- (08048657) --------------------------------------------------------
int get_unum()
{
    int v1[3]; // [esp+1Ch] [ebp-Ch] BYREF

    v1[0] = 0;
    fflush(stdout);
    __isoc99_scanf(&unk_8048900, v1);
    clear_stdin();
    return v1[0];
}
// 8048560: using guessed type int __cdecl __isoc99_scanf(_DWORD, _DWORD);
// 8048657: using guessed type int var_C[3];

//----- (0804868F) --------------------------------------------------------
void __cdecl __noreturn prog_timeout(int a1)
{
    int v1; // eax

    v1 = sys_exit(1);
}

//----- (080486A0) --------------------------------------------------------
unsigned int enable_timeout_cons()
{
    signal(14, (__sighandler_t)prog_timeout);
    return alarm(0x3Cu);
}

//----- (080486C8) --------------------------------------------------------
int __cdecl main(int argc, const char** argv, const char** envp)
{
    int stat_loc; // [esp+1Ch] [ebp-9Ch] BYREF
    char s[128]; // [esp+20h] [ebp-98h] BYREF
    int v6; // [esp+A0h] [ebp-18h]
    int v7; // [esp+A4h] [ebp-14h]
    int v8; // [esp+A8h] [ebp-10h]
    __pid_t v9; // [esp+ACh] [ebp-Ch]

    v9 = fork();
    memset(s, 0, sizeof(s));
    v8 = 0;
    stat_loc = 0;
    if (v9) {
        do {
            wait(&stat_loc);
            v6 = stat_loc;
            if ((stat_loc & 0x7F) == 0 || (v7 = stat_loc, (char)((stat_loc & 0x7F) + 1) >> 1 > 0)) {
                puts("child is exiting...");
                return 0;
            }
            v8 = ptrace(PTRACE_PEEKUSER, v9, 44, 0);
        } while (v8 != 11);
        puts("no exec() for you");
        kill(v9, 9);
    } else {
        prctl(1, 1);
        ptrace(PTRACE_TRACEME, 0, 0, 0);
        puts("Give me some shellcode, k");
        gets(s);
    }
    return 0;
}

//----- (08048830) --------------------------------------------------------
void _libc_csu_init(void)
{
    int v0; // edi
    int i; // esi

    init_proc();
    v0 = ((char*)&_CTOR_LIST__ - ((char*)&GLOBAL_OFFSET_TABLE_ + (_DWORD)(&_init_array_start - 33630205))) >> 2;
    if (v0) {
        for (i = 0; i != v0; ++i)
            (*(&_init_array_start + i))();
    }
}
// 8049F00: using guessed type int (*_init_array_start)();
// 8049F04: using guessed type int _CTOR_LIST__;
// 8049FF4: using guessed type Elf32_Dyn *GLOBAL_OFFSET_TABLE_;

//----- (080488B0) --------------------------------------------------------
void (*_do_global_ctors_aux())(void)
{
    void (*result)(void); // eax
    void (**v1)(void); // ebx

    result = (void (*)(void))_CTOR_LIST__;
    if (_CTOR_LIST__ != -1) {
        v1 = (void (**)(void)) & _CTOR_LIST__;
        do {
            --v1;
            result();
            result = *v1;
        } while (*v1 != (void (*)(void)) - 1);
    }
    return result;
}
// 8049F04: using guessed type int _CTOR_LIST__;

//----- (080488DC) --------------------------------------------------------
void term_proc()
{
    _do_global_dtors_aux();
}

// nfuncs=43 queued=13 decompiled=13 lumina nreq=0 worse=0 better=0
// ALL OK, 13 function(s) have been successfully decompiled
