/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

//-------------------------------------------------------------------------
// Function declarations

void (*init_proc())(void);
__int64 sub_400660(); // weak
// int strncmp(const char *s1, const char *s2, size_t n);
// int puts(const char *s);
// size_t fread(void *ptr, size_t size, size_t n, FILE *stream);
// int fclose(FILE *stream);
// int system(const char *command);
// int printf(const char *format, ...);
// size_t strcspn(const char *s, const char *reject);
// int __fastcall __libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// char *fgets(char *s, int n, FILE *stream);
// FILE *fopen(const char *filename, const char *modes);
// void __noreturn exit(int status);
// size_t fwrite(const void *ptr, size_t size, size_t n, FILE *s);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
__int64 (**call_gmon_start())(void);
void _do_global_dtors_aux();
void frame_dummy();
int __fastcall main(int argc, const char** argv, const char** envp);
void _libc_csu_init(void); // idb
void _libc_csu_fini(void); // idb
void (*_do_global_ctors_aux())(void);
void term_proc();
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

__int64 _CTOR_LIST__ = -1LL; // weak
__int64 _DTOR_LIST__[] = { -1LL }; // weak
__int64 _DTOR_END__ = 0LL; // weak
__int64 (*qword_6011D0)(void) = NULL; // weak
FILE* stdin; // idb
FILE* stderr; // idb
char completed_6531; // weak
__int64 dtor_idx_6533; // weak

//----- (0000000000400640) ----------------------------------------------------
void (*init_proc())(void)
{
    call_gmon_start();
    frame_dummy();
    return _do_global_ctors_aux();
}

//----- (0000000000400660) ----------------------------------------------------
__int64 sub_400660()
{
    return qword_6011D0();
}
// 400660: using guessed type __int64 sub_400660();
// 6011D0: using guessed type __int64 (*qword_6011D0)(void);

//----- (0000000000400730) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
    __int64 v3; // rax
    int v4; // esi
    __int64 v5; // [rsp-8h] [rbp-8h] BYREF
    char* retaddr; // [rsp+0h] [rbp+0h] BYREF

    v4 = v5;
    v5 = v3;
    __libc_start_main(
        (int(__fastcall*)(int, char**, char**))main,
        v4,
        &retaddr,
        _libc_csu_init,
        _libc_csu_fini,
        a3,
        &v5);
    __halt();
}
// 400736: positive sp value 8 has been found
// 40073D: variable 'v3' is possibly undefined

//----- (000000000040075C) ----------------------------------------------------
__int64 (**call_gmon_start())(void)
{
    __int64 (**result)(void); // rax

    result = &_gmon_start__;
    if (&_gmon_start__)
        return (__int64 (**)(void))_gmon_start__();
    return result;
}
// 6012D0: using guessed type __int64 _gmon_start__(void);

//----- (0000000000400780) ----------------------------------------------------
void _do_global_dtors_aux()
{
    __int64 v0; // rax
    unsigned __int64 i; // rbx

    if (!completed_6531) {
        v0 = dtor_idx_6533;
        for (i = &_DTOR_END__ - _DTOR_LIST__ - 1; dtor_idx_6533 < i; v0 = dtor_idx_6533) {
            dtor_idx_6533 = v0 + 1;
            ((void (*)(void))_DTOR_LIST__[v0 + 1])();
        }
        completed_6531 = 1;
    }
}
// 601010: using guessed type __int64 _DTOR_LIST__[];
// 601018: using guessed type __int64 _DTOR_END__;
// 601258: using guessed type char completed_6531;
// 601260: using guessed type __int64 dtor_idx_6533;

//----- (00000000004007F0) ----------------------------------------------------
void frame_dummy()
{
    ;
}

//----- (0000000000400814) ----------------------------------------------------
int __fastcall main(int argc, const char** argv, const char** envp)
{
    char s2[96]; // [rsp+10h] [rbp-110h] BYREF
    int v5; // [rsp+70h] [rbp-B0h]
    char ptr[48]; // [rsp+80h] [rbp-A0h] BYREF
    char s[96]; // [rsp+B0h] [rbp-70h] BYREF
    int v8; // [rsp+110h] [rbp-10h]
    int v9; // [rsp+114h] [rbp-Ch]
    FILE* stream; // [rsp+118h] [rbp-8h]

    memset(s, 0, sizeof(s));
    v8 = 0;
    memset(ptr, 0, 41);
    memset(s2, 0, sizeof(s2));
    v5 = 0;
    stream = 0LL;
    v9 = 0;
    stream = fopen("/home/users/level03/.pass", "r");
    if (!stream) {
        fwrite("ERROR: failed to open password file\n", 1uLL, 0x24uLL, stderr);
        exit(1);
    }
    v9 = fread(ptr, 1uLL, 0x29uLL, stream);
    ptr[strcspn(ptr, "\n")] = 0;
    if (v9 != 41) {
        fwrite("ERROR: failed to read password file\n", 1uLL, 0x24uLL, stderr);
        fwrite("ERROR: failed to read password file\n", 1uLL, 0x24uLL, stderr);
        exit(1);
    }
    fclose(stream);
    puts("===== [ Secure Access System v1.0 ] =====");
    puts("/***************************************\\");
    puts("| You must login to access this system. |");
    puts("\\**************************************/");
    printf("--[ Username: ");
    fgets(s, 100, stdin);
    s[strcspn(s, "\n")] = 0;
    printf("--[ Password: ");
    fgets(s2, 100, stdin);
    s2[strcspn(s2, "\n")] = 0;
    puts("*****************************************");
    if (strncmp(ptr, s2, 0x29uLL)) {
        printf(s);
        puts(" does not have access!");
        exit(1);
    }
    printf("Greetings, %s!\n", s);
    system("/bin/sh");
    return 0;
}
// 400814: using guessed type char s[96];
// 400814: using guessed type char ptr[48];
// 400814: using guessed type char s2[96];

//----- (0000000000400AC0) ----------------------------------------------------
void _libc_csu_init(void)
{
    init_proc();
}

//----- (0000000000400B60) ----------------------------------------------------
void (*_do_global_ctors_aux())(void)
{
    void (*result)(void); // rax
    void (**v1)(void); // rbx

    result = (void (*)(void))_CTOR_LIST__;
    if (_CTOR_LIST__ != -1) {
        v1 = (void (**)(void)) & _CTOR_LIST__;
        do {
            --v1;
            result();
            result = *v1;
        } while (*v1 != (void (*)(void)) - 1LL);
    }
    return result;
}
// 601000: using guessed type __int64 _CTOR_LIST__;

//----- (0000000000400B98) ----------------------------------------------------
void term_proc()
{
    _do_global_dtors_aux();
}

// nfuncs=36 queued=10 decompiled=10 lumina nreq=0 worse=0 better=0
// ALL OK, 10 function(s) have been successfully decompiled
