/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

//-------------------------------------------------------------------------
// Function declarations

void (*init_proc())(void);
int sub_8048470();
// int printf(const char *format, ...);
// int fflush(FILE *stream);
// int getchar(void);
// time_t time(time_t *timer);
// int puts(const char *s);
// int system(const char *command);
// int __gmon_start__(void); weak
// void srand(unsigned int seed);
// int __cdecl __libc_start_main(int (__cdecl *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int rand(void);
// int __isoc99_scanf(const char *, ...); weak
// void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>);
void _do_global_dtors_aux();
int frame_dummy();
int clear_stdin();
int get_unum();
void __noreturn prog_timeout(); // weak
int __cdecl decrypt(char a1);
int __cdecl test(int a1, int a2);
int __cdecl main(int argc, const char** argv, const char** envp);
void _libc_csu_fini(void); // idb
void (*_do_global_ctors_aux())(void);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN _libc_csu_init;
int _CTOR_LIST__[] = { -1 }; // weak
int _DTOR_LIST__[] = { -1 }; // weak
int _DTOR_END__ = 0; // weak
int _JCR_LIST__ = 0; // weak
Elf32_Dyn* GLOBAL_OFFSET_TABLE_ = &DYNAMIC; // weak
int (*dword_8049FFC)(void) = NULL; // weak
FILE* stdout; // idb
char completed_6159; // weak
int dtor_idx_6161; // weak
// extern _UNKNOWN _gmon_start__; weak

//----- (0804843C) --------------------------------------------------------
void (*init_proc())(void)
{
    if (&_gmon_start__)
        __gmon_start__();
    frame_dummy();
    return _do_global_ctors_aux();
}
// 80484F0: using guessed type int __gmon_start__(void);

//----- (08048470) --------------------------------------------------------
int sub_8048470()
{
    return dword_8049FFC();
}
// 8049FFC: using guessed type int (*dword_8049FFC)(void);

//----- (08048540) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(int a1 @<eax>, void (*a2)(void) @<edx>)
{
    int v2; // esi
    int v3; // [esp-4h] [ebp-4h] BYREF
    char* retaddr; // [esp+0h] [ebp+0h] BYREF

    v2 = v3;
    v3 = a1;
    __libc_start_main(
        (int(__cdecl*)(int, char**, char**))main,
        v2,
        &retaddr,
        (void (*)(void))_libc_csu_init,
        _libc_csu_fini,
        a2,
        &v3);
    __halt();
}
// 8048543: positive sp value 4 has been found

//----- (08048570) --------------------------------------------------------
void _do_global_dtors_aux()
{
    int v0; // eax
    unsigned int i; // ebx

    if (!completed_6159) {
        v0 = dtor_idx_6161;
        for (i = &_DTOR_END__ - _DTOR_LIST__ - 1; dtor_idx_6161 < i; v0 = dtor_idx_6161) {
            dtor_idx_6161 = v0 + 1;
            ((void (*)(void))_DTOR_LIST__[v0 + 1])();
        }
        completed_6159 = 1;
    }
}
// 8049F1C: using guessed type int _DTOR_LIST__[];
// 8049F20: using guessed type int _DTOR_END__;
// 804A044: using guessed type char completed_6159;
// 804A048: using guessed type int dtor_idx_6161;

//----- (080485D0) --------------------------------------------------------
int frame_dummy()
{
    int result; // eax

    result = _JCR_LIST__;
    if (_JCR_LIST__)
        return 0;
    return result;
}
// 8049F24: using guessed type int _JCR_LIST__;

//----- (080485F4) --------------------------------------------------------
int clear_stdin()
{
    int result; // eax

    do
        result = getchar();
    while ((_BYTE)result != 10 && (_BYTE)result != 0xFF);
    return result;
}

//----- (08048617) --------------------------------------------------------
int get_unum()
{
    int v1[3]; // [esp+1Ch] [ebp-Ch] BYREF

    v1[0] = 0;
    fflush(stdout);
    __isoc99_scanf("%u", v1);
    clear_stdin();
    return v1[0];
}
// 8048530: using guessed type int __isoc99_scanf(const char *, ...);
// 8048617: using guessed type int var_C[3];

//----- (0804864F) --------------------------------------------------------
void __noreturn prog_timeout()
{
    int v0; // eax

    v0 = sys_exit(1);
}
// 804864F: using guessed type void __noreturn prog_timeout();

//----- (08048660) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int __cdecl decrypt(char a1)
{
    unsigned int i; // [esp+20h] [ebp-28h]
    unsigned int v3; // [esp+24h] [ebp-24h]
    char v4[29]; // [esp+2Bh] [ebp-1Dh] BYREF

    *(_DWORD*)&v4[17] = __readgsdword(0x14u);
    strcpy(v4, "Q}|u`sfg~sf{}|a3");
    v3 = strlen(v4);
    for (i = 0; i < v3; ++i)
        v4[i] ^= a1;
    if (!strcmp(v4, "Congratulations!"))
        return system("/bin/sh");
    else
        return puts("\nInvalid Password");
}
// 8048746: positive sp value 4 has been found

//----- (08048747) --------------------------------------------------------
int __cdecl test(int a1, int a2)
{
    int result; // eax
    char v3; // al

    switch (a2 - a1) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
        result = decrypt(a2 - a1);
        break;
    default:
        v3 = rand();
        result = decrypt(v3);
        break;
    }
    return result;
}

//----- (0804885A) --------------------------------------------------------
int __cdecl main(int argc, const char** argv, const char** envp)
{
    unsigned int v3; // eax
    int savedregs; // [esp+20h] [ebp+0h] BYREF

    v3 = time(0);
    srand(v3);
    puts("***********************************");
    puts("*\t\tlevel03\t\t**");
    puts("***********************************");
    printf("Password:");
    __isoc99_scanf("%d", &savedregs);
    test(savedregs, 322424845);
    return 0;
}
// 8048530: using guessed type int __isoc99_scanf(const char *, ...);

//----- (080488F0) --------------------------------------------------------
void __cdecl _libc_csu_init(int a1, int a2, int a3)
{
    int v3; // edi
    int i; // esi

    init_proc();
    v3 = (134520820 - (int)&GLOBAL_OFFSET_TABLE_) >> 2;
    if (v3) {
        for (i = 0; i != v3; ++i)
            ((void(__cdecl*)(int, int, int))_CTOR_LIST__[i])(a1, a2, a3);
    }
}
// 8049F14: using guessed type int _CTOR_LIST__[];
// 8049FF4: using guessed type Elf32_Dyn *GLOBAL_OFFSET_TABLE_;

//----- (08048970) --------------------------------------------------------
void (*_do_global_ctors_aux())(void)
{
    void (*result)(void); // eax
    void (**v1)(void); // ebx

    result = (void (*)(void))_CTOR_LIST__[0];
    if (_CTOR_LIST__[0] != -1) {
        v1 = (void (**)(void))_CTOR_LIST__;
        do {
            --v1;
            result();
            result = *v1;
        } while (*v1 != (void (*)(void)) - 1);
    }
    return result;
}
// 8049F14: using guessed type int _CTOR_LIST__[];

//----- (0804899C) --------------------------------------------------------
void term_proc()
{
    _do_global_dtors_aux();
}

// nfuncs=40 queued=14 decompiled=14 lumina nreq=0 worse=0 better=0
// ALL OK, 14 function(s) have been successfully decompiled
