/* This file was generated by the Hex-Rays decompiler version 8.4.0.240320.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

//-------------------------------------------------------------------------
// Function declarations

void (*init_proc())(void);
int sub_8048460();
// int printf(const char *format, ...);
// int fflush(FILE *stream);
// int getchar(void);
// char *fgets(char *s, int n, FILE *stream);
// int puts(const char *s);
// int __gmon_start__(void); weak
// int __cdecl __libc_start_main(int (__cdecl *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// void *memset(void *s, int c, size_t n);
// int __cdecl __isoc99_scanf(_DWORD, _DWORD); weak
// void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>);
void _do_global_dtors_aux();
int frame_dummy();
int clear_stdin();
int get_unum();
void __noreturn prog_timeout(); // weak
int __cdecl store_number(int a1);
int __cdecl read_number(int a1);
int __cdecl main(int argc, const char** argv, const char** envp);
void _libc_csu_fini(void); // idb
void (*_do_global_ctors_aux())(void);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN _libc_csu_init;
_UNKNOWN unk_8048AD0; // weak
int _CTOR_LIST__[] = { -1 }; // weak
int _DTOR_LIST__[] = { -1 }; // weak
int _DTOR_END__ = 0; // weak
int _JCR_LIST__ = 0; // weak
Elf32_Dyn* GLOBAL_OFFSET_TABLE_ = &DYNAMIC; // weak
int (*dword_8049FFC)(void) = NULL; // weak
FILE* stdin; // idb
FILE* stdout; // idb
char completed_6159; // weak
int dtor_idx_6161; // weak
// extern _UNKNOWN _gmon_start__; weak

//----- (0804842C) --------------------------------------------------------
void (*init_proc())(void)
{
    if (&_gmon_start__)
        __gmon_start__();
    frame_dummy();
    return _do_global_ctors_aux();
}
// 80484D0: using guessed type int __gmon_start__(void);

//----- (08048460) --------------------------------------------------------
int sub_8048460()
{
    return dword_8049FFC();
}
// 8049FFC: using guessed type int (*dword_8049FFC)(void);

//----- (08048510) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(int a1 @<eax>, void (*a2)(void) @<edx>)
{
    int v2; // esi
    int v3; // [esp-4h] [ebp-4h] BYREF
    char* retaddr; // [esp+0h] [ebp+0h] BYREF

    v2 = v3;
    v3 = a1;
    __libc_start_main(
        (int(__cdecl*)(int, char**, char**))main,
        v2,
        &retaddr,
        (void (*)(void))_libc_csu_init,
        _libc_csu_fini,
        a2,
        &v3);
    __halt();
}
// 8048513: positive sp value 4 has been found

//----- (08048540) --------------------------------------------------------
void _do_global_dtors_aux()
{
    int v0; // eax
    unsigned int i; // ebx

    if (!completed_6159) {
        v0 = dtor_idx_6161;
        for (i = &_DTOR_END__ - _DTOR_LIST__ - 1; dtor_idx_6161 < i; v0 = dtor_idx_6161) {
            dtor_idx_6161 = v0 + 1;
            ((void (*)(void))_DTOR_LIST__[v0 + 1])();
        }
        completed_6159 = 1;
    }
}
// 8049F1C: using guessed type int _DTOR_LIST__[];
// 8049F20: using guessed type int _DTOR_END__;
// 804A064: using guessed type char completed_6159;
// 804A068: using guessed type int dtor_idx_6161;

//----- (080485A0) --------------------------------------------------------
int frame_dummy()
{
    int result; // eax

    result = _JCR_LIST__;
    if (_JCR_LIST__)
        return 0;
    return result;
}
// 8049F24: using guessed type int _JCR_LIST__;

//----- (080485C4) --------------------------------------------------------
int clear_stdin()
{
    int result; // eax

    do
        result = getchar();
    while ((_BYTE)result != 10 && (_BYTE)result != 0xFF);
    return result;
}

//----- (080485E7) --------------------------------------------------------
int get_unum()
{
    int v1[3]; // [esp+1Ch] [ebp-Ch] BYREF

    v1[0] = 0;
    fflush(stdout);
    __isoc99_scanf(&unk_8048AD0, v1);
    clear_stdin();
    return v1[0];
}
// 8048500: using guessed type int __cdecl __isoc99_scanf(_DWORD, _DWORD);
// 80485E7: using guessed type int var_C[3];

//----- (0804861F) --------------------------------------------------------
void __noreturn prog_timeout()
{
    int v0; // eax

    v0 = sys_exit(1);
}
// 804861F: using guessed type void __noreturn prog_timeout();

//----- (08048630) --------------------------------------------------------
int __cdecl store_number(int a1)
{
    unsigned int unum; // [esp+18h] [ebp-10h]
    unsigned int v3; // [esp+1Ch] [ebp-Ch]

    printf(" Number: ");
    unum = get_unum();
    printf(" Index: ");
    v3 = get_unum();
    if (v3 == 3 * (v3 / 3) || HIBYTE(unum) == 183) {
        puts(" *** ERROR! ***");
        puts("   This index is reserved for wil!");
        puts(" *** ERROR! ***");
        return 1;
    } else {
        *(_DWORD*)(a1 + 4 * v3) = unum;
        return 0;
    }
}

//----- (080486D7) --------------------------------------------------------
int __cdecl read_number(int a1)
{
    int unum; // [esp+1Ch] [ebp-Ch]

    printf(" Index: ");
    unum = get_unum();
    printf(" Number at data[%u] is %u\n", unum, *(_DWORD*)(a1 + 4 * unum));
    return 0;
}

//----- (08048723) --------------------------------------------------------
int __cdecl main(int argc, const char** argv, const char** envp)
{
    _BYTE v6[400]; // [esp+24h] [ebp-1B8h] BYREF
    int number; // [esp+1B4h] [ebp-28h]
    char s[4]; // [esp+1B8h] [ebp-24h] BYREF
    int v9; // [esp+1BCh] [ebp-20h]
    int v10; // [esp+1C0h] [ebp-1Ch]
    int v11; // [esp+1C4h] [ebp-18h]
    int v12; // [esp+1C8h] [ebp-14h]
    unsigned int v13; // [esp+1CCh] [ebp-10h]

    v13 = __readgsdword(0x14u);
    number = 0;
    *(_DWORD*)s = 0;
    v9 = 0;
    v10 = 0;
    v11 = 0;
    v12 = 0;
    memset(v6, 0, sizeof(v6));
    while (*argv) {
        memset((void*)*argv, 0, strlen(*argv));
        ++argv;
    }
    while (*envp) {
        memset((void*)*envp, 0, strlen(*envp));
        ++envp;
    }
    puts(
        "----------------------------------------------------\n"
        "  Welcome to wil's crappy number storage service!   \n"
        "----------------------------------------------------\n"
        " Commands:                                          \n"
        "    store - store a number into the data storage    \n"
        "    read  - read a number from the data storage     \n"
        "    quit  - exit the program                        \n"
        "----------------------------------------------------\n"
        "   wil has reserved some storage :>                 \n"
        "----------------------------------------------------\n");
    while (1) {
        printf("Input command: ");
        number = 1;
        fgets(s, 20, stdin);
        s[strlen(s) - 1] = 0;
        if (!memcmp(s, "store", 5u)) {
            number = store_number((int)v6);
            goto LABEL_13;
        }
        if (!memcmp(s, "read", 4u)) {
            number = read_number((int)v6);
            goto LABEL_13;
        }
        if (!memcmp(s, "quit", 4u))
            return 0;
    LABEL_13:
        if (number)
            printf(" Failed to do %s command\n", s);
        else
            printf(" Completed %s command successfully\n", s);
        *(_DWORD*)s = 0;
        v9 = 0;
        v10 = 0;
        v11 = 0;
        v12 = 0;
    }
}
// 8048723: using guessed type char s[4];

//----- (08048A00) --------------------------------------------------------
void __cdecl _libc_csu_init(int a1, int a2, int a3)
{
    int v3; // edi
    int i; // esi

    init_proc();
    v3 = (134520820 - (int)&GLOBAL_OFFSET_TABLE_) >> 2;
    if (v3) {
        for (i = 0; i != v3; ++i)
            ((void(__cdecl*)(int, int, int))_CTOR_LIST__[i])(a1, a2, a3);
    }
}
// 8049F14: using guessed type int _CTOR_LIST__[];
// 8049FF4: using guessed type Elf32_Dyn *GLOBAL_OFFSET_TABLE_;

//----- (08048A80) --------------------------------------------------------
void (*_do_global_ctors_aux())(void)
{
    void (*result)(void); // eax
    void (**v1)(void); // ebx

    result = (void (*)(void))_CTOR_LIST__[0];
    if (_CTOR_LIST__[0] != -1) {
        v1 = (void (**)(void))_CTOR_LIST__;
        do {
            --v1;
            result();
            result = *v1;
        } while (*v1 != (void (*)(void)) - 1);
    }
    return result;
}
// 8049F14: using guessed type int _CTOR_LIST__[];

//----- (08048AAC) --------------------------------------------------------
void term_proc()
{
    _do_global_dtors_aux();
}

// nfuncs=36 queued=14 decompiled=14 lumina nreq=0 worse=0 better=0
// ALL OK, 14 function(s) have been successfully decompiled
