/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

//-------------------------------------------------------------------------
// Function declarations

void (*init_proc())(void);
int sub_8048330();
// int printf(const char *format, ...);
// char *fgets(char *s, int n, FILE *stream);
// int __gmon_start__(void); weak
// void exit(int status);
// int __cdecl __libc_start_main(int (__cdecl *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>);
void _do_global_dtors_aux();
int frame_dummy();
int __cdecl main(int argc, const char** argv, const char** envp);
void _libc_csu_fini(void); // idb
void (*_do_global_ctors_aux())(void);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN _libc_csu_init;
int _CTOR_LIST__[] = { -1 }; // weak
int _DTOR_LIST__[] = { -1 }; // weak
int _DTOR_END__ = 0; // weak
int _JCR_LIST__ = 0; // weak
Elf32_Dyn* GLOBAL_OFFSET_TABLE_ = &DYNAMIC; // weak
int (*dword_80497D0)(void) = NULL; // weak
FILE* stdin; // idb
char completed_6159; // weak
int dtor_idx_6161; // weak
// extern _UNKNOWN _gmon_start__; weak

//----- (080482F8) --------------------------------------------------------
void (*init_proc())(void)
{
    if (&_gmon_start__)
        __gmon_start__();
    frame_dummy();
    return _do_global_ctors_aux();
}
// 8048360: using guessed type int __gmon_start__(void);

//----- (08048330) --------------------------------------------------------
int sub_8048330()
{
    return dword_80497D0();
}
// 80497D0: using guessed type int (*dword_80497D0)(void);

//----- (08048390) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(int a1 @<eax>, void (*a2)(void) @<edx>)
{
    int v2; // esi
    int v3; // [esp-4h] [ebp-4h] BYREF
    char* retaddr; // [esp+0h] [ebp+0h] BYREF

    v2 = v3;
    v3 = a1;
    __libc_start_main(
        (int(__cdecl*)(int, char**, char**))main,
        v2,
        &retaddr,
        (void (*)(void))_libc_csu_init,
        _libc_csu_fini,
        a2,
        &v3);
    __halt();
}
// 8048393: positive sp value 4 has been found

//----- (080483C0) --------------------------------------------------------
void _do_global_dtors_aux()
{
    int v0; // eax
    unsigned int i; // ebx

    if (!completed_6159) {
        v0 = dtor_idx_6161;
        for (i = &_DTOR_END__ - _DTOR_LIST__ - 1; dtor_idx_6161 < i; v0 = dtor_idx_6161) {
            dtor_idx_6161 = v0 + 1;
            ((void (*)(void))_DTOR_LIST__[v0 + 1])();
        }
        completed_6159 = 1;
    }
}
// 80496F0: using guessed type int _DTOR_LIST__[];
// 80496F4: using guessed type int _DTOR_END__;
// 80497F4: using guessed type char completed_6159;
// 80497F8: using guessed type int dtor_idx_6161;

//----- (08048420) --------------------------------------------------------
int frame_dummy()
{
    int result; // eax

    result = _JCR_LIST__;
    if (_JCR_LIST__)
        return 0;
    return result;
}
// 80496F8: using guessed type int _JCR_LIST__;

//----- (08048444) --------------------------------------------------------
int __cdecl __noreturn main(int argc, const char** argv, const char** envp)
{
    char s[100]; // [esp+28h] [ebp-70h] BYREF
    unsigned int i; // [esp+8Ch] [ebp-Ch]

    i = 0;
    fgets(s, 100, stdin);
    for (i = 0; i < strlen(s); ++i) {
        if (s[i] > 64 && s[i] <= 90)
            s[i] ^= 0x20u;
    }
    printf(s);
    exit(0);
}
// 8048444: using guessed type char s[100];

//----- (08048520) --------------------------------------------------------
void __cdecl _libc_csu_init(int a1, int a2, int a3)
{
    int v3; // edi
    int i; // esi

    init_proc();
    v3 = (134518728 - (int)&GLOBAL_OFFSET_TABLE_) >> 2;
    if (v3) {
        for (i = 0; i != v3; ++i)
            ((void(__cdecl*)(int, int, int))_CTOR_LIST__[i])(a1, a2, a3);
    }
}
// 80496E8: using guessed type int _CTOR_LIST__[];
// 80497C8: using guessed type Elf32_Dyn *GLOBAL_OFFSET_TABLE_;

//----- (080485A0) --------------------------------------------------------
void (*_do_global_ctors_aux())(void)
{
    void (*result)(void); // eax
    void (**v1)(void); // ebx

    result = (void (*)(void))_CTOR_LIST__[0];
    if (_CTOR_LIST__[0] != -1) {
        v1 = (void (**)(void))_CTOR_LIST__;
        do {
            --v1;
            result();
            result = *v1;
        } while (*v1 != (void (*)(void)) - 1);
    }
    return result;
}
// 80496E8: using guessed type int _CTOR_LIST__[];

//----- (080485CC) --------------------------------------------------------
void term_proc()
{
    _do_global_dtors_aux();
}

// nfuncs=21 queued=9 decompiled=9 lumina nreq=0 worse=0 better=0
// ALL OK, 9 function(s) have been successfully decompiled
