//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int32_t verify_user_name(void);
int32_t verify_user_pass(int32_t* a1);

// --------------------- Global Variables ---------------------

struct _IO_FILE* g1 = NULL; // 0x804a020
char* g2; // 0x804a040

// ------------------------ Functions -------------------------

// Address range: 0x8048464 - 0x80484a3
int32_t verify_user_name(void)
{
    // 0x8048464
    puts("verifying username....\n");
    bool v1; // 0x8048464
    int32_t v2 = v1 ? -1 : 1; // 0x804848b
    int32_t v3 = (int32_t) "dat_wil"; // 0x8048464
    int32_t v4 = (int32_t)&g2; // 0x8048464
    int32_t v5 = 7; // 0x804848b
    unsigned char v6 = *(char*)v4; // 0x804848b
    char v7 = *(char*)v3; // 0x804848b
    char v8 = v7; // 0x804848b
    bool v9 = false; // 0x804848b
    while (v6 == v7) {
        v5--;
        v3 += v2;
        v4 += v2;
        v8 = v6;
        v9 = true;
        if (v5 == 0) {
            // break ->
            break;
        }
        v6 = *(char*)v4;
        v7 = *(char*)v3;
        v8 = v7;
        v9 = false;
    }
    unsigned char v10 = v8;
    return (int32_t) !((v6 < v10 | v9)) - (int32_t)(v6 < v10);
}

// Address range: 0x80484a3 - 0x80484d0
int32_t verify_user_pass(int32_t* a1)
{
    // 0x80484a3
    bool v1; // 0x80484a3
    int32_t v2 = v1 ? -1 : 1; // 0x80484bb
    int32_t v3 = (int32_t) "admin"; // 0x80484a3
    int32_t v4 = (int32_t)a1; // 0x80484a3
    int32_t v5 = 5; // 0x80484bb
    unsigned char v6 = *(char*)v4; // 0x80484bb
    char v7 = *(char*)v3; // 0x80484bb
    char v8 = v7; // 0x80484bb
    bool v9 = false; // 0x80484bb
    while (v6 == v7) {
        v5--;
        v3 += v2;
        v4 += v2;
        v8 = v6;
        v9 = true;
        if (v5 == 0) {
            // break ->
            break;
        }
        v6 = *(char*)v4;
        v7 = *(char*)v3;
        v8 = v7;
        v9 = false;
    }
    unsigned char v10 = v8;
    return (int32_t) !((v6 < v10 | v9)) - (int32_t)(v6 < v10);
}

// Address range: 0x80484d0 - 0x80485b6
int main(int argc, char** argv)
{
    // 0x80484d0
    int32_t str; // bp-84, 0x80484d0
    __asm_rep_stosd_memset((char*)&str, 0, 16);
    puts("********* ADMIN LOGIN PROMPT *********");
    printf("Enter Username: ");
    fgets((char*)&g2, 256, g1);
    if (verify_user_name() == 0) {
        // 0x8048550
        puts("Enter Password: ");
        fgets((char*)&str, 100, g1);
        verify_user_pass(&str);
        puts("nope, incorrect password...\n");
    } else {
        // 0x804853d
        puts("nope, incorrect username...\n");
    }
    // 0x80485af
    return 1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.5.x)
// Detected functions: 3
